# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1hk64hggwghi1fg3f00hzaj4axz2lw1alwl10zqsp61gj0jfw8k6";
    x86_64-linux = "1p2l73624lic5vqbml48i5kxial230xhqqzfpskrmswjz6dsrxr7";
    aarch64-linux = "1fvy2ypspzasb46hq5fnxxp90ygzr7hh76jxhhhl8xmizvc5hyls";
    x86_64-darwin = "0iazdkn7rk93amrgywhlmpqbjiz950srjfl3yzm9s053r3j9n76b";
    aarch64-darwin = "1dy9dg8fisbc6rj2ks76zg55rrmh9z35pkxpzv10ymqi987ga6ld";
  };

  urlMap = {
    i686-linux = "https://github.com/pokanop/nostromo/releases/download/v0.14.2/nostromo_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/pokanop/nostromo/releases/download/v0.14.2/nostromo_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/pokanop/nostromo/releases/download/v0.14.2/nostromo_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/pokanop/nostromo/releases/download/v0.14.2/nostromo_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/pokanop/nostromo/releases/download/v0.14.2/nostromo_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "nostromo";
  version = "0.14.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    runHook preInstall
    mkdir -p $out/bin
    cp -vr ./nostromo $out/bin/nostromo
    runHook postInstall
  '';

  meta = {
    description = "CLI to manage aliases through simple commands to add and remove scoped aliases and substitutions.";
    homepage = "https://nostromo.sh";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
